{% from "dockers/dockerfile-macros.j2" import install_debian_packages, install_python_wheels, copy_files %}
FROM docker-config-engine-bullseye-{{DOCKER_USERNAME}}:{{DOCKER_USERTAG}}

ARG docker_container_name
ARG image_version

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive

# Pass the image_version to container
ENV IMAGE_VERSION=$image_version

RUN apt-get update



## Clean up
RUN apt-get clean -y        && \
    apt-get autoclean -y    && \
    apt-get autoremove -y   && \
    rm -rf /debs
COPY ["docker-init.sh", "/usr/bin/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
COPY ["files/supervisor-proc-exit-listener", "/usr/bin"]
COPY ["critical_processes", "/etc/supervisor"]
COPY ["cli", "/cli/"]

# ARG manifest

# RUN apt-get update

# COPY ["docker-init.sh", "/usr/bin/"]
# COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
# COPY ["files/supervisor-proc-exit-listener", "/usr/bin"]
# COPY ["critical_processes", "/etc/supervisor"]
# COPY ["cli", "/cli/"]

# LABEL com.azure.sonic.manifest="$manifest"

ENTRYPOINT ["/usr/local/bin/supervisord"]