## Docker image for Prometheus monitoring

DOCKER_PROMETHEUS_STEM = docker-prometheus
DOCKER_PROMETHEUS = $(DOCKER_PROMETHEUS_STEM).gz
DOCKER_PROMETHEUS_DBG = $(DOCKER_PROMETHEUS_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_PROMETHEUS)_PATH = $(DOCKERS_PATH)/$(DOCKER_PROMETHEUS_STEM)

# Basic dependencies
# $(DOCKER_PROMETHEUS)_DEPENDS += $(LIBSWSSCOMMON)
# $(DOCKER_PROMETHEUS)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_DEPENDS)
# $(DOCKER_PROMETHEUS)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BOOKWORM)_DBG_IMAGE_PACKAGES)
# $(DOCKER_PROMETHEUS)_LOAD_DOCKERS = $(DOCKER_CONFIG_ENGINE_BOOKWORM)

# $(DOCKER_PROMETHEUS)_INSTALL_PYTHON_WHEELS = $(SONIC_UTILITIES_PY3)
# $(DOCKER_PROMETHEUS)_INSTALL_DEBS = $(PYTHON3_SWSSCOMMON)
# $(DOCKER_PROMETHEUS)_PYTHON_WHEELS += $(SONIC_DHCP_UTILITIES_PY3)

# Version and package info  
$(DOCKER_PROMETHEUS)_VERSION = 3.2.1
$(DOCKER_PROMETHEUS)_PACKAGE_NAME = prometheus
$(DOCKER_PROMETHEUS)_PACKAGE_DEPENDS = database^1.0.0

$(DOCKER_PROMETHEUS)_SERVICE_REQUIRES = config-setup
$(DOCKER_PROMETHEUS)_SERVICE_AFTER = swss 
$(DOCKER_PROMETHEUS)_SERVICE_DEPENDENT_OF = swss

# Add to main package lists
SONIC_DOCKER_IMAGES += $(DOCKER_PROMETHEUS)
SONIC_DOCKER_DBG_IMAGES += $(DOCKER_PROMETHEUS_DBG)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_EVENTD)

ifeq ($(INCLUDE_KUBERNETES),y)
$(DOCKER_PROMETHEUS)_DEFAULT_FEATURE_OWNER = kube
endif

$(DOCKER_PROMETHEUS)_DEFAULT_FEATURE_STATE_ENABLED = y


SONIC_PACKAGES_LOCAL += $(DOCKER_PROMETHEUS)
SONIC_PACKAGES_LOCAL += $(DOCKER_PROMETHEUS_DBG)

# Container configuration
$(DOCKER_PROMETHEUS)_CONTAINER_NAME = prometheus
$(DOCKER_PROMETHEUS)_CONTAINER_PRIVILEGED = false

# Volume mounts
$(DOCKER_PROMETHEUS)_CONTAINER_VOLUMES += /etc/sonic:/etc/sonic:ro
$(DOCKER_PROMETHEUS)_CONTAINER_VOLUMES += /etc/prometheus:/etc/prometheus:ro
$(DOCKER_PROMETHEUS)_CONTAINER_VOLUMES += /prometheus:/prometheus

# Port mapping for Prometheus UI
$(DOCKER_PROMETHEUS)_CONTAINER_PORTS += 9090:9090

# Temp directories
$(DOCKER_PROMETHEUS)_CONTAINER_TMPFS += /tmp/
$(DOCKER_PROMETHEUS)_CONTAINER_TMPFS += /var/tmp/

$(DOCKER_PROMETHEUS)_SQUASH = n


$(DOCKER_PROMETHEUS)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)